name: .NET Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Clear Binaries
      shell: pwsh
      run: |
           if (Test-Path -Path FastXL\bin) { \
               Remove-Item FastXL\bin -Force -Recurse \
           }

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --no-restore --verbosity normal --configuration Release
   
    - name: Pack Package
      shell: pwsh
      run: dotnet pack --no-build --no-restore --include-source --configuration Release

    - name: Push Package
      run: dotnet nuget push FastXL/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json